vim.g.mapleader = ' '
require("plugins")
require("colorscheme")
require("nvim_tree")
require("telescope_plugin")
require("settings")
require("flutter")
require("cmp_snippets")
require("dashboard")
-- require("bar")
require("status_line")
